### ISSUE TITLE
it returns an activeX alert when opened by using IE

### ISSUE THREAD

**Issue by ghoobber** [JohnnyBeGood34/JQuery-AnimateSlider#2]
Hi, as the title suggest, it returns an activeX alert when opened by using IE

**Comment by JohnnyBeGood34** [comment]
Hi, What kind of warning? It's probably because you're running the page locally. IE doesn't like local pages to run javascript and will always complain about it. Once you have it as a website (even on localhost) it shouldn't complain anymore.

**Comment by ghoobber** [comment]
Ah ok you're right. Thanks
